spring.application.name=pokemanager


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

resilience4j.retry.instances.pokeApi.max-attempts=3
resilience4j.retry.instances.pokeApi.wait-duration=500ms
resilience4j.retry.instances.pokeApi.retry-exceptions=com.sxeix.pokemanager.infrastructure.pokeapi.PokeApiClientException
resilience4j.retry.instances.pokeApi.ignore-exceptions=com.sxeix.pokemanager.infrastructure.pokeapi.PokeApiNonRetryableException